import { SUPABASE_URL, SUPABASE_ANON_KEY, supabaseIsConfigured } from './supabase-config.js';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const db = supabaseIsConfigured ? createClient(SUPABASE_URL, SUPABASE_ANON_KEY, { auth: { persistSession: true, autoRefreshToken: true } }) : null;
const page = document.body.dataset.page;
const $ = (s, root = document) => root.querySelector(s);
const esc = (value = '') => String(value).replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c]));
const icon = name => `<i data-lucide="${name}"></i>`;

function refreshIcons() { window.lucide?.createIcons(); }
function toast(message, type = '') { const el = $('#toast'); if (!el) return; el.textContent = message; el.className = `toast show ${type}`; clearTimeout(toast.timer); toast.timer = setTimeout(() => el.className = 'toast', 3200); }
function dateText(value) { return new Intl.DateTimeFormat('ka-GE', { dateStyle: 'medium' }).format(new Date(value)); }
function neutralError(error, fallback = 'მოქმედება ვერ შესრულდა. სცადეთ ხელახლა.') { console.error(error); return fallback; }
function configuredMessage(target) { target.innerHTML = `<div class="empty-state">${icon('settings')}<h2>Supabase ჯერ არ არის კონფიგურირებული</h2><p>დაამატეთ პროექტის URL და anon key <code>supabase-config.js</code>-ში, შემდეგ გაუშვით schema SQL.</p></div>`; refreshIcons(); }

function initChrome() { document.querySelectorAll('[data-year]').forEach(el => el.textContent = new Date().getFullYear()); const button = $('.menu-toggle'); if (button) button.addEventListener('click', () => { const nav = $('nav'); const open = nav.classList.toggle('open'); button.setAttribute('aria-expanded', open); }); refreshIcons(); }
function card(project) { const image = project.image_url ? `<img src="${esc(project.image_url)}" alt="${esc(project.title)}" loading="lazy">` : `<div class="card-image fallback">${icon('circuit-board')}</div>`; return `<article class="project-card"><div class="card-image">${image}</div><div class="card-body"><div class="card-meta"><span>${esc(project.category)}</span><time datetime="${esc(project.created_at)}">${dateText(project.created_at)}</time></div><h2>${esc(project.title)}</h2><p>${esc(project.description)}</p><div class="card-footer"><span>${icon('user-round')} ${esc(project.author)}</span><a class="text-link" href="project.html?id=${encodeURIComponent(project.id)}">ნახვა ${icon('arrow-up-right')}</a></div></div></article>`; }

async function initProjects() { const status = $('#projects-status'), grid = $('#projects-grid'); if (!db) return configuredMessage(status); const { data, error } = await db.from('projects').select('id,title,description,category,author,image_url,created_at').eq('published', true).order('created_at', { ascending: false }).limit(60); if (error) { status.textContent = neutralError(error, 'პროექტების ჩატვირთვა ვერ მოხერხდა.'); return; } status.remove(); const render = () => { const q = $('#project-search').value.trim().toLocaleLowerCase('ka'); const category = $('#category-filter').value; const result = data.filter(p => (!category || p.category === category) && (!q || `${p.title} ${p.description} ${p.author}`.toLocaleLowerCase('ka').includes(q))); grid.innerHTML = result.length ? result.map(card).join('') : `<div class="empty-state full">${icon('search-x')}<h2>${data.length ? 'პროექტი ვერ მოიძებნა' : 'ჯერ პროექტები არ დამატებულა'}</h2><p>${data.length ? 'შეცვალეთ ძიება ან ფილტრი.' : 'როგორც კი ადმინისტრატორი პირველ პროექტს გამოაქვეყნებს, ის აქ გამოჩნდება.'}</p></div>`; refreshIcons(); }; $('#project-search').addEventListener('input', render); $('#category-filter').addEventListener('change', render); render(); }

async function initDetail() { const target = $('#project-detail'); if (!db) return configuredMessage(target); const id = new URLSearchParams(location.search).get('id'); if (!id || !/^[0-9a-f-]{36}$/i.test(id)) return notFound(target); const { data: p, error } = await db.from('projects').select('*').eq('id', id).eq('published', true).maybeSingle(); if (error || !p) return notFound(target); const image = p.image_url ? `<img class="detail-image" src="${esc(p.image_url)}" alt="${esc(p.title)}">` : ''; const video = p.video_url ? `<section class="detail-section media-section"><h2>${icon('video')} ვიდეო</h2><video controls preload="metadata" src="${esc(p.video_url)}">თქვენი ბრაუზერი ვიდეოს არ უჭერს მხარს.</video></section>` : ''; const components = p.components ? `<section class="detail-section"><h2>${icon('package')} საჭირო კომპონენტები</h2><div class="prose lines">${esc(p.components)}</div></section>` : ''; const how = p.how_it_was_made ? `<section class="detail-section"><h2>${icon('wrench')} როგორ გაკეთდა</h2><div class="prose lines">${esc(p.how_it_was_made)}</div></section>` : ''; const code = p.code ? `<section class="detail-section"><div class="code-heading"><h2>${icon('braces')} Arduino Code</h2><button id="copy-code" class="button secondary compact">${icon('copy')} კოდის დაკოპირება</button></div><pre><code id="arduino-code">${esc(p.code)}</code></pre></section>` : ''; target.className = ''; target.innerHTML = `<article class="detail"><div class="detail-hero"><div><div class="card-meta"><span>${esc(p.category)}</span><time>${dateText(p.created_at)}</time></div><h1>${esc(p.title)}</h1><p>${esc(p.description)}</p><div class="author-line">${icon('user-round')} ${esc(p.author)}</div></div>${image}</div><div class="detail-content">${components}${how}${video}${code}</div></article>`; $('#copy-code')?.addEventListener('click', async () => { try { await navigator.clipboard.writeText(p.code); toast('კოდი დაკოპირდა', 'success'); } catch { toast('კოდის დაკოპირება ვერ მოხერხდა.'); } }); refreshIcons(); }
function notFound(target) { target.className = ''; target.innerHTML = `<div class="empty-state">${icon('search-x')}<h2>პროექტი ვერ მოიძებნა</h2><p>ბმული არასწორია ან პროექტი აღარ არის გამოქვეყნებული.</p><a href="projects.html" class="button primary">პროექტებზე დაბრუნება</a></div>`; refreshIcons(); }

const IMAGE_TYPES = ['image/jpeg', 'image/png', 'image/webp', 'image/gif']; const VIDEO_TYPES = ['video/mp4', 'video/webm', 'video/ogg'];
function fileOkay(file, types, max, label) { if (!file) return true; if (!types.includes(file.type)) { toast(`${label}: ფაილის ტიპი მიუღებელია.`); return false; } if (file.size > max) { toast(`${label}: ფაილი ზედმეტად დიდია.`); return false; } return true; }
async function isAdmin(user) { if (!user || !db) return null; const { data, error } = await db.from('admin_users').select('username').eq('user_id', user.id).maybeSingle(); if (error || !data) return null; return data; }
async function initAdmin() { if (!db) { $('#auth-panel').querySelector('form').hidden = true; $('#login-error').textContent = 'Supabase ჯერ არ არის კონფიგურირებული.'; return; } const { data: { session } } = await db.auth.getSession(); if (session) await showDashboard(session.user); $('#login-form').addEventListener('submit', login); $('#logout-button')?.addEventListener('click', logout); $('#new-project-button')?.addEventListener('click', () => openEditor()); $('#cancel-edit')?.addEventListener('click', closeEditor); $('#project-form')?.addEventListener('submit', saveProject); $('#image-file')?.addEventListener('change', imagePreview); $('#video-file')?.addEventListener('change', () => { $('#video-name').textContent = $('#video-file').files[0]?.name || 'ფაილი არჩეული არ არის'; }); db.auth.onAuthStateChange((_event, session) => { if (!session) showLogin(); }); }
async function login(event) { event.preventDefault(); const form = event.currentTarget, button = form.querySelector('button'); $('#login-error').textContent = ''; setBusy(button, true, 'იტვირთება...'); const { data, error } = await db.auth.signInWithPassword({ email: $('#login-email').value.trim(), password: $('#login-password').value }); if (error || !data.user) { $('#login-error').textContent = 'მონაცემები არასწორია'; setBusy(button, false); return; } const admin = await isAdmin(data.user); if (!admin) { await db.auth.signOut(); $('#login-error').textContent = 'ამ ანგარიშს ადმინისტრატორის წვდომა არ აქვს.'; setBusy(button, false); return; } await showDashboard(data.user, admin); }
async function showDashboard(user, knownAdmin) { const admin = knownAdmin || await isAdmin(user); if (!admin) { if (user) await db.auth.signOut(); return showLogin(); } $('#auth-panel').hidden = true; $('#dashboard').hidden = false; $('#admin-name').textContent = admin.username; refreshIcons(); await loadAdminProjects(); }
function showLogin() { $('#dashboard').hidden = true; $('#auth-panel').hidden = false; closeEditor(); }
async function logout() { await db.auth.signOut(); toast('თქვენ გამოხვედით ანგარიშიდან.'); }
function setBusy(button, busy, text) { button.disabled = busy; if (busy) { button.dataset.label = button.innerHTML; button.textContent = text; } else if (button.dataset.label) button.innerHTML = button.dataset.label; refreshIcons(); }
let adminProjects = [];
async function loadAdminProjects() { const status = $('#admin-status'), list = $('#admin-project-list'); status.hidden = false; list.innerHTML = ''; const { data, error } = await db.from('projects').select('id,title,category,published,created_at,author,image_url,video_url,description,components,how_it_was_made,code').order('created_at', { ascending: false }); if (error) { status.textContent = neutralError(error, 'პროექტების ჩატვირთვა ვერ მოხერხდა.'); return; } adminProjects = data; status.hidden = true; $('#admin-count').textContent = `${data.length} პროექტი`; list.innerHTML = data.length ? data.map(p => `<article class="admin-row"><div><h3>${esc(p.title)}</h3><p>${esc(p.category)} · ${dateText(p.created_at)}</p></div><span class="status ${p.published ? 'published' : 'hidden-status'}">${p.published ? 'გამოქვეყნებული' : 'დამალული'}</span><div class="row-actions"><a class="icon-button" title="ნახვა" href="project.html?id=${p.id}">${icon('eye')}</a><button class="icon-button edit" data-id="${p.id}" title="რედაქტირება">${icon('pencil')}</button><button class="icon-button toggle" data-id="${p.id}" title="${p.published ? 'დამალვა' : 'გამოქვეყნება'}">${icon(p.published ? 'eye-off' : 'send')}</button><button class="icon-button danger delete" data-id="${p.id}" title="წაშლა">${icon('trash-2')}</button></div></article>`).join('') : `<div class="empty-state compact-empty">${icon('folder-plus')}<h2>ჯერ პროექტები არ დამატებულა</h2><p>დაიწყეთ პირველი რეალური პროექტის დამატებით.</p></div>`; list.querySelectorAll('.edit').forEach(b => b.addEventListener('click', () => openEditor(adminProjects.find(p => p.id === b.dataset.id)))); list.querySelectorAll('.toggle').forEach(b => b.addEventListener('click', () => togglePublished(b.dataset.id))); list.querySelectorAll('.delete').forEach(b => b.addEventListener('click', () => deleteProject(b.dataset.id))); refreshIcons(); }
function openEditor(p) { const form = $('#project-form'); form.reset(); $('#image-preview').hidden = true; $('#image-name').textContent = 'ფაილი არჩეული არ არის'; $('#video-name').textContent = 'ფაილი არჩეული არ არის'; $('#form-error').textContent = ''; $('#editor-title').textContent = p ? 'პროექტის რედაქტირება' : 'ახალი პროექტი'; $('#save-project').innerHTML = p ? `ცვლილებების შენახვა ${icon('save')}` : `პროექტის დამატება ${icon('save')}`; if (p) { $('#edit-id').value=p.id; $('#title').value=p.title; $('#category').value=p.category; $('#author').value=p.author; $('#published').checked=p.published; $('#description').value=p.description; $('#components').value=p.components || ''; $('#how-made').value=p.how_it_was_made || ''; $('#code').value=p.code || ''; } $('#project-editor').hidden=false; $('#project-editor').scrollIntoView({ behavior:'smooth', block:'start' }); refreshIcons(); }
function closeEditor() { const editor = $('#project-editor'); if (editor) editor.hidden=true; }
function imagePreview() { const file = $('#image-file').files[0]; $('#image-name').textContent = file?.name || 'ფაილი არჩეული არ არის'; if (file && fileOkay(file, IMAGE_TYPES, 5 * 1024 * 1024, 'სურათი')) { const preview=$('#image-preview'); preview.src=URL.createObjectURL(file); preview.hidden=false; } }
async function upload(file, bucket, folder, types, max, label) { if (!file) return null; if (!fileOkay(file, types, max, label)) throw new Error('invalid-file'); const clean = file.name.replace(/[^a-zA-Z0-9._-]/g, '_'); const path = `${folder}/${crypto.randomUUID()}-${clean}`; const { error } = await db.storage.from(bucket).upload(path, file, { cacheControl:'3600', upsert:false, contentType:file.type }); if (error) throw error; const { data } = db.storage.from(bucket).getPublicUrl(path); return { url:data.publicUrl, path }; }
function storagePath(url, bucket) { try { const marker=`/storage/v1/object/public/${bucket}/`; const index=url?.indexOf(marker); return index >= 0 ? decodeURIComponent(url.slice(index + marker.length)) : null; } catch { return null; } }
async function removeStored(url, bucket) { const path=storagePath(url,bucket); if (path) { const { error }=await db.storage.from(bucket).remove([path]); if (error) console.warn('Storage cleanup failed', error); } }
async function saveProject(event) { event.preventDefault(); const button=$('#save-project'), id=$('#edit-id').value, old=adminProjects.find(p=>p.id===id), image=$('#image-file').files[0], video=$('#video-file').files[0]; $('#form-error').textContent=''; if (!fileOkay(image,IMAGE_TYPES,5*1024*1024,'სურათი') || !fileOkay(video,VIDEO_TYPES,50*1024*1024,'ვიდეო')) return; setBusy(button,true,'ინახება...'); let uploads=[]; try { const folder=id || crypto.randomUUID(); if(image) uploads.push(['image', await upload(image,'project-images',folder,IMAGE_TYPES,5*1024*1024,'სურათი')]); if(video) uploads.push(['video', await upload(video,'project-videos',folder,VIDEO_TYPES,50*1024*1024,'ვიდეო')]); const value={title:$('#title').value.trim(), category:$('#category').value, author:$('#author').value.trim(), description:$('#description').value.trim(), components:$('#components').value.trim() || null, how_it_was_made:$('#how-made').value.trim() || null, code:$('#code').value || null, published:$('#published').checked}; const img=uploads.find(x=>x[0]==='image')?.[1], vid=uploads.find(x=>x[0]==='video')?.[1]; if(img) value.image_url=img.url; if(vid) value.video_url=vid.url; let error; if(id) ({error}=await db.from('projects').update(value).eq('id',id)); else ({error}=await db.from('projects').insert(value)); if(error) throw error; if(img && old?.image_url) await removeStored(old.image_url,'project-images'); if(vid && old?.video_url) await removeStored(old.video_url,'project-videos'); toast(id ? 'ცვლილებები შენახულია.' : 'პროექტი დაემატა.', 'success'); closeEditor(); await loadAdminProjects(); } catch(error) { console.error(error); for (const [kind, file] of uploads) await removeStored(file.url,kind==='image'?'project-images':'project-videos'); $('#form-error').textContent=neutralError(error,'პროექტის შენახვა ვერ მოხერხდა.'); } finally { setBusy(button,false); } }
async function togglePublished(id) { const p=adminProjects.find(x=>x.id===id); const {error}=await db.from('projects').update({published:!p.published}).eq('id',id); if(error) return toast('სტატუსის შეცვლა ვერ მოხერხდა.'); toast(p.published?'პროექტი დამალულია.':'პროექტი გამოქვეყნდა.','success'); loadAdminProjects(); }
async function deleteProject(id) { const p=adminProjects.find(x=>x.id===id); if(!p || !confirm('ნამდვილად გსურთ ამ პროექტის წაშლა?')) return; const {error}=await db.from('projects').delete().eq('id',id); if(error) return toast('პროექტის წაშლა ვერ მოხერხდა.'); await Promise.all([removeStored(p.image_url,'project-images'),removeStored(p.video_url,'project-videos')]); toast('პროექტი წაიშალა.','success'); loadAdminProjects(); }

async function initPasswordReset() { const form = $('#reset-password-form'); if (!db) { $('#reset-error').textContent = 'Supabase ჯერ არ არის კონფიგურირებული.'; form.querySelector('button').disabled = true; return; } form.addEventListener('submit', async event => { event.preventDefault(); const error = $('#reset-error'), password = $('#new-password').value, confirmPassword = $('#confirm-password').value, button = form.querySelector('button'); error.textContent = ''; if (password !== confirmPassword) { error.textContent = 'პაროლები ერთმანეთს არ ემთხვევა.'; return; } if (password.length < 10) { error.textContent = 'პაროლი მინიმუმ 10 სიმბოლო უნდა იყოს.'; return; } const { data: { session } } = await db.auth.getSession(); if (!session) { error.textContent = 'აღდგენის ბმული არასწორია ან ვადა გაუვიდა. მოითხოვეთ ახალი ბმული.'; return; } setBusy(button, true, 'ინახება...'); const { error: updateError } = await db.auth.updateUser({ password }); if (updateError) error.textContent = 'პაროლის შეცვლა ვერ მოხერხდა. მოითხოვეთ ახალი ბმული.'; else { toast('პაროლი წარმატებით შეიცვალა.', 'success'); setTimeout(() => location.href = 'admin.html', 900); } setBusy(button, false); }); }

initChrome(); if(page==='projects') initProjects(); if(page==='detail') initDetail(); if(page==='admin') initAdmin(); if(page==='reset') initPasswordReset();
